### ISSUE TITLE
Make regions world-specific

### ISSUE THREAD

**Issue by jackah2** [whimc/Science-Tools#6]
WorldGuard regions are currently checked by name. Since regions are world-specific, the plugin should also require the world name to specify a region.

Current path (`tools.TOOL.regions.REGION`):
```yaml
regions:
  example: 1
```

New proposed path (`tools.TOOL.regions.WORLD.REGION`):
```yaml
regions:
  world:
    example: 1
  world_end:
    example: 5
```
